# Employee Performance Analysis

#### Code: 10281
### INX Future Inc.

# PREDICT_MODEL

## Importing Libraries

In [19]:
import pandas as pd
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

## Loading Test Data

In [20]:
X_test = pd.read_excel("X_test.xlsx")
y_test = pd.read_excel("y_test.xlsx")

## Loading Models

In [21]:
lr_model = joblib.load("logistic_model.pkl")
dt_model = joblib.load("decision_tree_model.pkl")
rf_model = joblib.load("random_forest_model.pkl")
gb_model = joblib.load("gradient_boosting_model.pkl")

## Making Predictions

In [22]:
lr_pred = lr_model.predict(X_test)
dt_pred = dt_model.predict(X_test)
rf_pred = rf_model.predict(X_test)
gb_pred = gb_model.predict(X_test)

## SAVING PREDICTIONS

In [23]:
predictions = pd.DataFrame({
    'Actual': y_test.values.flatten(),
    'Logistic': lr_pred,
    'DecisionTree': dt_pred,
    'RandomForest': rf_pred,
    'GradientBoosting': gb_pred
})

predictions.to_excel("model_predictions_xtest_data.xlsx", index=False)

In [24]:
predictions

     Actual  Logistic  DecisionTree  RandomForest  GradientBoosting
0         3         3             3             3                 3
1         3         3             3             3                 3
2         2         3             3             3                 3
3         2         3             2             3                 2
4         3         3             3             3                 3
..      ...       ...           ...           ...               ...
235       2         3             2             2                 2
236       3         3             3             3                 3
237       3         3             3             3                 3
238       3         3             3             3                 3
239       2         2             2             2                 2

[240 rows x 5 columns]

# USE y_test FOR EVALUATION

## Accuracy Scores

In [25]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_pred))

Logistic Regression Accuracy: 0.8208333333333333
Decision Tree Accuracy: 0.9375
Random Forest Accuracy: 0.8958333333333334
Gradient Boosting Accuracy: 0.9416666666666667

## Classification Report

In [26]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           2       0.90      0.69      0.78        39
           3       0.89      0.98      0.93       175
           4       1.00      0.62      0.76        26

    accuracy                           0.90       240
   macro avg       0.93      0.76      0.83       240
weighted avg       0.90      0.90      0.89       240

In [27]:
print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           2       0.92      0.87      0.89        39
           3       0.94      0.98      0.96       175
           4       1.00      0.77      0.87        26

    accuracy                           0.94       240
   macro avg       0.95      0.87      0.91       240
weighted avg       0.94      0.94      0.94       240

In [28]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           2       0.89      0.85      0.87        39
           3       0.94      0.98      0.96       175
           4       0.95      0.81      0.88        26

    accuracy                           0.94       240
   macro avg       0.93      0.88      0.90       240
weighted avg       0.94      0.94      0.94       240

In [29]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           2       0.67      0.46      0.55        39
           3       0.84      0.95      0.89       175
           4       0.87      0.50      0.63        26

    accuracy                           0.82       240
   macro avg       0.79      0.64      0.69       240
weighted avg       0.81      0.82      0.81       240

## Confusion Matrix

In [30]:
print(confusion_matrix(y_test, gb_pred))
print(confusion_matrix(y_test, dt_pred))
print(confusion_matrix(y_test, rf_pred))
print(confusion_matrix(y_test, lr_pred))

[[ 34   5   0]
 [  3 172   0]
 [  0   6  20]]
[[ 33   6   0]
 [  3 171   1]
 [  1   4  21]]
[[ 27  12   0]
 [  3 172   0]
 [  0  10  16]]
[[ 18  20   1]
 [  8 166   1]
 [  1  12  13]]

# SAVING RESULTS WITH y_test

## Combining Actual + Predictions

### Converting y_test to 1D

In [31]:
y_test = y_test.values.ravel()

In [32]:
predictions_1 = pd.DataFrame({
    'Actual': y_test,
    'Logistic': lr_pred,
    'DecisionTree': dt_pred,
    'RandomForest': rf_pred,
    'GradientBoosting': gb_pred
})

predictions_1.to_excel("model_predictions_Ytest_data.xlsx", index=False)

In [33]:
predictions_1

     Actual  Logistic  DecisionTree  RandomForest  GradientBoosting
0         3         3             3             3                 3
1         3         3             3             3                 3
2         2         3             3             3                 3
3         2         3             2             3                 2
4         3         3             3             3                 3
..      ...       ...           ...           ...               ...
235       2         3             2             2                 2
236       3         3             3             3                 3
237       3         3             3             3                 3
238       3         3             3             3                 3
239       2         2             2             2                 2

[240 rows x 5 columns]

## Function to Plot & Save

In [34]:
def plot_and_save_cm(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    
    plt.title(f"{model_name} Confusion Matrix")
    
    plt.savefig(f"{model_name}_cm.png")  
    plt.close()

## Generating & Save All

In [35]:
plot_and_save_cm(y_test, lr_pred, "Logistic")
plot_and_save_cm(y_test, dt_pred, "DecisionTree")
plot_and_save_cm(y_test, rf_pred, "RandomForest")
plot_and_save_cm(y_test, gb_pred, "GradientBoosting")