# Getting data from the database

## Installing necessary libraries

In [19]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\navee\anaconda3\lib\site-packages (9.6.0)

In [20]:
import mysql.connector

In [28]:
conn = mysql.connector.connect(
    host="projects.datamites.com",
    user="dm_usdata_sql",
    password="37z<49REb&mKnl4AV!vJ",
    database="project_service_data"
)

C:\Users\navee\AppData\Local\Temp\ipykernel_17840\2291339889.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql("SELECT * FROM service_data", conn)

  invoice_date job_card_date business_partner_name  vehicle_no  \
0     30-05-17      30-05-17        shivXXXXXXXXXX  KA03MFXXXX
1     02-06-17      31-05-17        KIRAXXXXXXXXXX  KA53ESXXXX
2     02-06-17      31-05-17        KIRAXXXXXXXXXX  KA53ESXXXX
3     02-06-17      31-05-17        KIRAXXXXXXXXXX  KA53ESXXXX
4     02-06-17      31-05-17        KIRAXXXXXXXXXX  KA53ESXXXX

              vehicle_model current_km_reading invoice_line_text
0  BAJAJ AVENGER STREET 220              50000        ENGINE OIL
1       BAJAJ PULSAR NS 200                758        ENGINE OIL
2       BAJAJ PULSAR NS 200                758            POLISH
3       BAJAJ PULSAR NS 200                758       CONSUMABLES
4       BAJAJ PULSAR NS 200                758       COOLANT OIL

# creating dataframe

In [ ]:
data = pd.read_sql("SELECT * FROM service_data", conn)

print(data.head())

conn.close()

In [29]:
data

,invoice_date,job_card_date,business_partner_name,vehicle_no,vehicle_model,current_km_reading,invoice_line_text
0,30-05-17,30-05-17,shivXXXXXXXXXX,KA03MFXXXX,BAJAJ AVENGER STREET 220,50000,ENGINE OIL
1,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,ENGINE OIL
2,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,POLISH
3,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,CONSUMABLES
4,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,COOLANT OIL
...,...,...,...,...,...,...,...
28477,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,SPROCKET RUBBER
28478,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,CLUTCH CABLE
28479,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,OIL FILTER
28480,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,DISC OIL
28481,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,AIR FILTER

In [30]:
# saving data in csv format

data.to_csv("data.csv", index=False)

In [33]:
inventory_data = pd.read_csv("C:\\Users\\navee\\Downloads\\Live_project\\project_client\\data\\data.csv")

In [34]:
inventory_data

,invoice_date,job_card_date,business_partner_name,vehicle_no,vehicle_model,current_km_reading,invoice_line_text
0,30-05-17,30-05-17,shivXXXXXXXXXX,KA03MFXXXX,BAJAJ AVENGER STREET 220,50000,ENGINE OIL
1,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,ENGINE OIL
2,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,POLISH
3,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,CONSUMABLES
4,02-06-17,31-05-17,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758,COOLANT OIL
...,...,...,...,...,...,...,...
28477,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,SPROCKET RUBBER
28478,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,CLUTCH CABLE
28479,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,OIL FILTER
28480,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,DISC OIL
28481,06-01-19,06-01-19,pravXXXXXXXXXX,KA53EVXXXX,BAJAJ DISCOVER 125,12805,AIR FILTER