# **PRCP-1020-HousePricePred**

**Team-ID : PTID-CDS-DEC-25-3526**

**Domain : Real-Estate**

# Problem Statement

Task 1:- Prepare a complete data analysis report on the given data.

Task 2:-

a) Create a robust machine learning algorithm to accurately predict the price of the house given the various factors across the market. 

b) Determine the relationship between the house features and how the price varies based on this.

Task3:- Come up with suggestions for the customer to buy the house according to the area, price and other requirements.

### What problem are you trying to answer?

The goal is to **predict the sale price of residential houses** based on their physical characteristics, location, condition, and sale-related attributes.
By analyzing historical housing data, we aim to understand **which factors most strongly influence house prices** and build a model that can accurately estimate the **SalePrice** for new or unseen properties.

---

### What does success look like?

Success is achieved when:

* The predictive model **accurately estimates house prices** with low error (e.g., low RMSE or MAE on validation/test data)
* The model **generalizes well** to unseen data (no overfitting)
* Key drivers of house prices (e.g., location, quality, size) are **clearly identified and interpretable**
* The results can be **reliably used for pricing decisions** or valuation analysis

From a business and analytics perspective, success means:

* Improved **pricing accuracy**
* Reduced **underpricing or overpricing risk**
* Actionable insights into **price-driving features**

---

### Who will use the result?

The results can be used by:

* **Real estate analysts** for property valuation and market analysis
* **Real estate agents** to recommend competitive listing prices
* **Home buyers and sellers** to assess fair market value
* **Data scientists and ML engineers** for model development and deployment
* **Financial institutions** for mortgage risk assessment and loan approvals

---

# Dataset Link: 

Link : https://d3ilbtxij3aepc.cloudfront.net/projects/CDS-Capstone-Projects/PRCP-1020-HousePricePred.zip

# Data Description: 

Attribute Information:

●	SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict.<br>
●	MSSubClass: The building class<br>
●	MSZoning: The general zoning classification<br>
●	LotFrontage: Linear feet of street connected to property<br>
●	LotArea: Lot size in square feet<br>
●	Street: Type of road access<br>
●	Alley: Type of alley access<br>
●	LotShape: General shape of property<br>
●	LandContour: Flatness of the property<br>
●	Utilities: Type of utilities available<br>
●	LotConfig: Lot configuration<br>
●	LandSlope: Slope of property<br>
●	Neighborhood: Physical locations within Ames city limits<br>
●	Condition1: Proximity to main road or railroad<br>
●	Condition2: Proximity to main road or railroad (if a second is present)<br>
●	BldgType: Type of dwelling<br>
●	HouseStyle: Style of dwelling<br>
●	OverallQual: Overall material and finish quality<br>
●	OverallCond: Overall condition rating<br>
●	YearBuilt: Original construction date<br>
●	YearRemodAdd: Remodel date<br>
●	RoofStyle: Type of roof<br>
●	RoofMatl: Roof material<br>
●	Exterior1st: Exterior covering on house<br>
●	Exterior2nd: Exterior covering on house (if more than one material)<br>
●	MasVnrType: Masonry veneer type<br>
●	MasVnrArea: Masonry veneer area in square feet<br>
●	ExterQual: Exterior material quality<br>
●	ExterCond: Present condition of the material on the exterior<br>
●	Foundation: Type of foundation<br>
●	BsmtQual: Height of the basement<br>
●	BsmtCond: General condition of the basement<br>
●	BsmtExposure: Walkout or garden level basement walls<br>
●	BsmtFinType1: Quality of basement finished area<br>
●	BsmtFinSF1: Type 1 finished square feet<br>
●	BsmtFinType2: Quality of second finished area (if present)<br>
●	BsmtFinSF2: Type 2 finished square feet<br>
●	BsmtUnfSF: Unfinished square feet of basement area<br>
●	TotalBsmtSF: Total square feet of basement area<br>
●	Heating: Type of heating<br>
●	HeatingQC: Heating quality and condition<br>
●	CentralAir: Central air conditioning<br>
●	Electrical: Electrical system<br>
●	1stFlrSF: First Floor square feet<br>
●	2ndFlrSF: Second floor square feet<br>
●	LowQualFinSF: Low quality finished square feet (all floors)<br>
●	GrLivArea: Above grade (ground) living area square feet<br>
●	BsmtFullBath: Basement full bathrooms<br>
●	BsmtHalfBath: Basement half bathrooms<br>
●	FullBath: Full bathrooms above grade<br>
●	HalfBath: Half baths above grade<br>
●	Bedroom: Number of bedrooms above basement level<br>
●	Kitchen: Number of kitchens<br>
●	KitchenQual: Kitchen quality<br>
●	TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)<br>
●	Functional: Home functionality rating<br>
●	Fireplaces: Number of fireplaces<br>
●	FireplaceQu: Fireplace quality<br>
●	GarageType: Garage location<br>
●	GarageYrBlt: Year garage was built<br>
●	GarageFinish: Interior finish of the garage<br>
●	GarageCars: Size of garage in car capacity<br>
●	GarageArea: Size of garage in square feet<br>
●	GarageQual: Garage quality<br>
●	GarageCond: Garage condition<br>
●	PavedDrive: Paved driveway<br>
●	WoodDeckSF: Wood deck area in square feet<br>
●	OpenPorchSF: Open porch area in square feet<br>
●	EnclosedPorch: Enclosed porch area in square feet<br>
●	3SsnPorch: Three season porch area in square feet<br>
●	ScreenPorch: Screen porch area in square feet<br>
●	PoolArea: Pool area in square feet<br>
●	PoolQC: Pool quality<br>
●	Fence: Fence quality<br>
●	MiscFeature: Miscellaneous feature not covered in other categories<br>
●	MiscVal: $Value of miscellaneous feature<br>
●	MoSold: Month Sold<br>
●	YrSold: Year Sold<br>
●	SaleType: Type of sale<br>
●	SaleCondition: Condition of sale<br>

# Model Comparison Report

Create a report stating the performance of multiple models for house price prediction and suggest the best model for production.

# Report on Challenges faced

Create a report which should include the challenges faced on data and what techniques were used with proper reasoning.

# **Data Dictionary**

- Data Dictionary is made for field and 'Domain' understanding:
<br>

# **House-price-pred_table**<br>
<br>

| Field Name    | Description                                           |
| ------------- | ----------------------------------------------------- |
| Id            | Unique identifier for each house                      |
| MSSubClass    | Identifies the type of dwelling involved in the sale  |
| MSZoning      | General zoning classification of the sale             |
| LotFrontage   | Linear feet of street connected to the property       |
| LotArea       | Lot size in square feet                               |
| Street        | Type of road access                                   |
| Alley         | Type of alley access                                  |
| LotShape      | General shape of property                             |
| LandContour   | Flatness of the property                              |
| Utilities     | Type of utilities available                           |
| LotConfig     | Lot configuration                                     |
| LandSlope     | Slope of property                                     |
| Neighborhood  | Physical locations within Ames city limits            |
| Condition1    | Proximity to main road or railroad                    |
| Condition2    | Proximity to secondary road or railroad               |
| BldgType      | Type of dwelling                                      |
| HouseStyle    | Style of dwelling                                     |
| OverallQual   | Overall material and finish quality                   |
| OverallCond   | Overall condition rating                              |
| YearBuilt     | Original construction date                            |
| YearRemodAdd  | Remodel date                                          |
| RoofStyle     | Type of roof                                          |
| RoofMatl      | Roof material                                         |
| Exterior1st   | Exterior covering on house                            |
| Exterior2nd   | Exterior covering on house                            |
| MasVnrType    | Masonry veneer type                                   |
| MasVnrArea    | Masonry veneer area in square feet                    |
| ExterQual     | Exterior material quality                             |
| ExterCond     | Exterior material condition                           |
| Foundation    | Type of foundation                                    |
| BsmtQual      | Height of basement                                    |
| BsmtCond      | General condition of basement                         |
| BsmtExposure  | Walkout or garden level basement walls                |
| BsmtFinType1  | Quality of basement finished area                     |
| BsmtFinSF1    | Type 1 finished square feet                           |
| BsmtFinType2  | Quality of second finished area                       |
| BsmtFinSF2    | Type 2 finished square feet                           |
| BsmtUnfSF     | Unfinished basement square feet                       |
| TotalBsmtSF   | Total basement square feet                            |
| Heating       | Type of heating                                       |
| HeatingQC     | Heating quality and condition                         |
| CentralAir    | Central air conditioning                              |
| Electrical    | Electrical system                                     |
| 1stFlrSF      | First floor square feet                               |
| 2ndFlrSF      | Second floor square feet                              |
| LowQualFinSF  | Low quality finished square feet                      |
| GrLivArea     | Above ground living area square feet                  |
| BsmtFullBath  | Basement full bathrooms                               |
| BsmtHalfBath  | Basement half bathrooms                               |
| FullBath      | Full bathrooms above grade                            |
| HalfBath      | Half baths above grade                                |
| BedroomAbvGr  | Bedrooms above grade                                  |
| KitchenAbvGr  | Kitchens above grade                                  |
| KitchenQual   | Kitchen quality                                       |
| TotRmsAbvGrd  | Total rooms above grade (excluding bathrooms)         |
| Functional    | Home functionality rating                             |
| Fireplaces    | Number of fireplaces                                  |
| FireplaceQu   | Fireplace quality                                     |
| GarageType    | Garage location                                       |
| GarageYrBlt   | Year garage was built                                 |
| GarageFinish  | Interior finish of the garage                         |
| GarageCars    | Size of garage in car capacity                        |
| GarageArea    | Size of garage in square feet                         |
| GarageQual    | Garage quality                                        |
| GarageCond    | Garage condition                                      |
| PavedDrive    | Paved driveway                                        |
| WoodDeckSF    | Wood deck area in square feet                         |
| OpenPorchSF   | Open porch area in square feet                        |
| EnclosedPorch | Enclosed porch area in square feet                    |
| 3SsnPorch     | Three-season porch area                               |
| ScreenPorch   | Screen porch area                                     |
| PoolArea      | Pool area in square feet                              |
| PoolQC        | Pool quality                                          |
| Fence         | Fence quality                                         |
| MiscFeature   | Miscellaneous feature not covered in other categories |
| MiscVal       | Value of miscellaneous feature                        |
| MoSold        | Month sold                                            |
| YrSold        | Year sold                                             |
| SaleType      | Type of sale                                          |
| SaleCondition | Condition of sale                                     |
| SalePrice     | Sale price of the property (TARGET VARIABLE)          |

# **Exploratory Data Analysis**

- **Load the data**

- **Inspect structure & data quality**

- **Perform statistical analysis**

- **Visualize key patterns**

- **Data analysis report**

# Importing necessary libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)

## Load Dataset

In [7]:
re_table = pd.read_csv("C:\\Users\\navee\\Downloads\\HousePricePred_P2\\Data\\data.csv")
re_table

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [8]:
re_table.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000